core/urls.py
from django.urls import path, include

from core import views
from rest_framework.routers import DefaultRouter


app_name = "core"
# router = DefaultRouter()
# router.register(r'api/posts', views.PostViewSet, basename="post")
# router.register(r'api/user', views.UserViewSet, basename="user")

urlpatterns = [
    path("", views.index, name='feed'),
    path("core/post/<slug:slug>/", views.post_detail, name='post-detail'),
    
    
    # Chat 
    
    path("core/inbox/", views.inbox, name="inbox"),
    path("core/inbox/<username>/", views.inbox_detail, name="inbox_detail"),
    
    
    # Group CHat
    path("core/group-inbox/", views.group_inbox, name="group_inbox"),
    path("core/create-group-chat/", views.create_group_chat, name="create_group_chat"),
    path("core/group-inbox/<slug:slug>/", views.group_inbox_detail, name="group_inbox_detail"),
    

    # Join & leave Group
    path("core/join-group-page/<slug:slug>/", views.join_group_chat_page, name="join_group_chat_page"),
    path("core/join-group-chat/<slug:slug>/", views.join_group_chat, name="join_group_chat"),
    path("core/leave-group/<slug:slug>/", views.leave_group_chat, name="leave_group_chat"),
    
    # Search
    path('search/', views.search_users, name='search_users'),
    
    
    # Groups, pages
    path('core/groups/', views.groups, name='groups'),
    path('core/group/<slug:slug>/', views.group_detail, name='group_detail'),
    path('core/groups/create/', views.create_group, name='create_group'),
    path('core/groups/create_post/<slug:group_slug>/', views.create_gr_post, name='create_group_post'),
    path("core/join-group/<slug:slug>/", views.join_group, name="join_group"),
    path("group/<slug:group_slug>/create_post/", views.create_gr_post, name='create_gr_post'),
    path("like_gr_post/", views.like_gr_post, name='like_gr_post'),
    path("comment_gr_post/", views.comment_gr_post, name='comment_gr_post'),
    path("like_gr_comment/", views.like_comment, name='like_gr_comment'),
    path("reply_gr_comment/", views.reply_gr_comment, name='reply_gr_comment'),
    path("delete_gr_comment/", views.delete_comment, name='delete_gr_comment'),
    path("delete_gr_reply/", views.delete_reply, name='delete_gr_reply'),
    path('core/pages/', views.pages, name='pages'),
    path('core/pages/create/', views.create_page, name='create_page'),

    path('core/page/<slug:slug>/', views.page_detail, name='page_detail'),
    
    #Ajax URLS
    path("create_post/", views.create_post, name='create_post'),
    path("delete_post/", views.delete_post, name='delete_post'),
    path("like_post/", views.like_post, name='like_post'),
    path("comment_post/", views.comment_on_post, name='comment_post'),
    path("like_comment/", views.like_comment, name='like_comment'),
    path("reply_comment/", views.reply_comment, name='reply_comment'),
    path("delete_comment/", views.delete_comment, name='delete_comment'),
    path("delete_reply/", views.delete_reply, name='delete_reply'),
    path("add_friend/", views.add_friend, name='add_friend'),
    path("accept_friend_request/", views.accept_friend_request, name='accept_friend_request'),
    path("reject_friend_request/", views.reject_friend_request, name='reject_friend_request'),
    path("unfriend/", views.unfriend, name='unfriend'),
    path("block_user/", views.block_user, name='block_user'),
    
    # Load more post
    path('load_more_posts/', views.load_more_posts, name='load_more_posts'),


    # api - rest framework
    # path("", include(router.urls)),
]

facebook_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from core.routing import websocket_urlpatterns
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    #routing
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    
    # Web socket
    path("ws/", include(websocket_urlpatterns)),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/chat/create_group_chat.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  <!-- Main Contents -->
  <div class="main_content">
    <div class="mcontainer">

        <!--  breadcrumb -->
        {% comment %} <div class="breadcrumb-area py-0">
            <div class="breadcrumb">
                <ul class="m-0">
                    <li>
                        <a href="{% url 'core:groups'%}">Groups</a>
                    </li>
                    <li class="active">
                        <a href="#">Create New Group Chat</a>
                    </li>
                </ul>
            </div>
        </div> {% endcomment %}


        <!-- create page-->
        <div class="max-w-2xl m-auto shadow-md rounded-md bg-white lg:mt-20">  
            <form id="group-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                <!-- form header -->
            <div class="text-center border-b border-gray-100 py-6">
                <h3 class="font-bold text-xl"> Create New Group Chat</h3>
            </div>

            <!-- form body -->
            <div class="p-10 space-y-7">

                <div class="line">
                    <input class="line__input" id="group-chat-name" name="group-chat-name" type="text" onkeyup="this.setAttribute('value', this.value);" value="" autocomplete="off">
                    <span for="username" class="line__placeholder"> Group Name </span>
                </div>

                <div class="line h-32"> 
                    <textarea class="line__input h-32"  id="group-chat-description" name="group-chat-description" type="text" onkeyup="this.setAttribute('value', this.value);" value="" autocomplete="off"></textarea>
                    <span for="username" class="line__placeholder"> Group description </span> 
                </div>

                <div class="px-2 space-y-2">
                    <label for="group-chat-members" class="font-semibold text-base"> Add Members </label>
                    <div>
                        {% for friend in request.user.profile.friends.all %}
                            <label class="flex items-center space-x-3">
                                <input type="checkbox" name="members[]" value="{{ friend.id }}" class="form-checkbox h-4 w-4 text-blue-600">
                                <img src="{{ friend.profile.image.url }}" alt="{{ friend.username }}" class="w-8 h-8 rounded-full">
                                <span>{{ friend.profile.full_name }}</span>
                            </label>
                        {% endfor %}
                    </div>
                </div>
                
            </div>
            
            <!-- form footer -->
            <div class="flex justify-center border-gray-100 py-8">
                <button type="submit" class="button lg:w-1/3">
                    Create Now
                </button>
            </div>
        </form>
        </div>


    </div>
</div>

</div>
{% endblock %}

templates/chat/group_inbox.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

    <!-- Main Contents -->
    <div class="main_content">

        <span uk-toggle="target: .message-content;" class="fixed left-0 top-36 bg-red-600 z-10 py-1 px-4 rounded-r-3xl text-white"> Users</span>

        <div class="messages-container">
            <div class="messages-container-inner">


                <div class="messages-inbox">
                    <div class="messages-headline">
                        <div class="input-with-icon" hidden>
                            <input id="autocomplete-input" type="text" placeholder="Search">
                            <i class="icon-material-outline-search"></i>
                        </div>
                        <h2 class="text-2xl font-semibold">Chats</h2>
                        <span class="absolute icon-feather-edit mr-4 text-xl uk-position-center-right cursor-pointer"></span>
                    </div>
                    <div class="messages-inbox-inner" data-simplebar>
                        <ul>
                            
                            {% for m in groupchat %}
                                <li>
                                    <a href="{% url 'core:group_inbox_detail' m.slug %}">
                                        <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{m.images.url}}" alt=""></div>

                                        <div class="message-by">
                                            <div class="message-by-headline">
                                                <h5>{{m.name}}</h5>
                                            </div>
                                            <p>{{m.last_message.message|truncatechars:40}}</p>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>


                <div class="message-content">

                    <div class="messages-headline">
                        <h4> All My Group Chats </h4>
                    </div>

                    <div class="message-content-scrolbar" data-simplebar>
                        <div class="message-content-inner">
                            <div class="card md:p-6 p-2 max-w-3xl mx-auto">
                                <div class="grid md:grid-cols-2  grid-cols-2 gap-x-2 gap-y-4 mt-3">
                                    
                                    {% for m in groupchat %}
                                        <div class="flex items-center flex-col md:flex-row justify-center p-4 rounded-md shadow hover:shadow-md md:space-x-4">
                                            <a href="{% url 'core:group_inbox_detail' m.slug %}" iv="" class="w-16 h-16 flex-shrink-0 overflow-hidden rounded-full relative">
                                                <img src="{{m.images.url}}" class="absolute w-full h-full inset-0 " alt="">
                                            </a>
                                            <div class="flex-4">
                                                <a href="{% url 'core:group_inbox_detail' m.slug %}" class="text-base font-semibold capitalize">{{m.name}} </a>
                                                <div class="text-sm text-gray-500"> {{m.members.all.count}} Members</div>
                                            </div>
                                            <a href="{% url 'core:group_inbox_detail' m.slug %}" class="bg-blue-500 text-white text-center font-semibold py-2 px-3 rounded-md text-sm md:mt-0 mt-3">Join Conversation</a>
                                        </div>
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- open chat box -->
    <div uk-toggle="target: #offcanvas-chat" class="start-chat">
        <svg class="h-7 w-7" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"></path>
        </svg>
    </div>

    <div id="offcanvas-chat" uk-offcanvas="flip: true; overlay: true">
        <div class="uk-offcanvas-bar bg-white p-0 w-full lg:w-80 shadow-2xl">


            <div class="relative pt-5 px-4">

                <h3 class="text-2xl font-bold mb-2"> Chats </h3>

                <div class="absolute right-3 top-4 flex items-center space-x-2">

                    <button class="uk-offcanvas-close  px-2 -mt-1 relative rounded-full inset-0 lg:hidden blcok" type="button" uk-close></button>

                    <a href="#" uk-toggle="target: #search;animation: uk-animation-slide-top-small">
                        <ion-icon name="search" class="text-xl hover:bg-gray-100 p-1 rounded-full"></ion-icon>
                    </a>
                    <a href="#">
                        <ion-icon name="settings-outline" class="text-xl hover:bg-gray-100 p-1 rounded-full"></ion-icon>
                    </a>
                    <a href="#">
                        <ion-icon name="ellipsis-vertical" class="text-xl hover:bg-gray-100 p-1 rounded-full"></ion-icon>
                    </a>
                    <div class="bg-white w-56 shadow-md mx-auto p-2 mt-12 rounded-md text-gray-500 hidden border border-gray-100 dark:bg-gray-900 dark:text-gray-100 dark:border-gray-700" uk-drop="mode: click;pos: bottom-right;animation: uk-animation-slide-bottom-small; offset:5">
                        <ul class="space-y-1">
                            <li>
                                <a href="#" class="flex items-center px-3 py-2 hover:bg-gray-100 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                    <ion-icon name="checkbox-outline" class="pr-2 text-xl"></ion-icon> Mark all as read
                                </a>
                            </li>
                            <li>
                                <a href="#" class="flex items-center px-3 py-2 hover:bg-gray-100 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                    <ion-icon name="settings-outline" class="pr-2 text-xl"></ion-icon> Chat setting
                                </a>
                            </li>
                            <li>
                                <a href="#" class="flex items-center px-3 py-2 hover:bg-gray-100 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                    <ion-icon name="notifications-off-outline" class="pr-2 text-lg"></ion-icon> Disable notifications
                                </a>
                            </li>
                            <li>
                                <a href="#" class="flex items-center px-3 py-2 hover:bg-gray-100 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                    <ion-icon name="star-outline" class="pr-2 text-xl"></ion-icon> Create a group chat
                                </a>
                            </li>
                        </ul>
                    </div>


                </div>


            </div>

            <div class="absolute bg-white z-10 w-full -mt-5 lg:-mt-2 transform translate-y-1.5 py-2 border-b items-center flex" id="search" hidden>
                <input type="text" placeholder="Search.." class="flex-1">
                <ion-icon name="close-outline" class="text-2xl hover:bg-gray-100 p-1 rounded-full mr-4 cursor-pointer" uk-toggle="target: #search;animation: uk-animation-slide-top-small"></ion-icon>
            </div>

            <nav class="responsive-nav border-b extanded mb-2 -mt-2">
                <ul uk-switcher="connect: #chats-tab; animation: uk-animation-fade">
                    <li class="uk-active"><a class="active" href="#0"> Friends  <span> {{request.user.profile.friends.all.count}} </span></a></li>
                    <li><a href="#0">Groups <span> {{groupchat.all.count}} </span> </a></li>
                </ul>
            </nav>

            <div class="contact-list px-2 uk-switcher" id="chats-tab">

                <div class="p-1">
                    {% for f in request.user.profile.friends.all  %}
                    
                        <a href="{% url 'core:inbox_detail' f.username%}">
                            <div class="contact-avatar">
                                <img src="{{f.profile.image.url}}" alt="">
                            </div>
                            <div class="contact-username"> {{f.profile.full_name}}</div>
                        </a>
                        
                    {% endfor %}


                </div>
                <div class="p-1">
                    {% for m in groupchat %}
                    
                        <a href="{% url 'core:group_inbox_detail' m.slug%}">
                            <div class="contact-avatar">
                                <img src="{{m.images.url}}" alt="">
                            </div>
                            <div class="contact-username">{{m.name}}</div>
                        </a>
                    {% endfor %}



                </div>

            </div>
        </div>
    </div>

    {% endblock content %}

templates/chat/group_inbox_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

    <!-- Main Contents -->
    <div class="main_content">

        <span uk-toggle="target: .message-content;" class="fixed left-0 top-36 bg-red-600 z-10 py-1 px-4 rounded-r-3xl text-white"> Users</span>

        <div class="messages-container">
            <div class="messages-container-inner">


                <div class="messages-inbox">
                    <div class="messages-headline">
                        <div class="input-with-icon" hidden>
                            <input id="autocomplete-input" type="text" placeholder="Search">
                            <i class="icon-material-outline-search"></i>
                        </div>
                        <h2 class="text-2xl font-semibold">Chats</h2>
                        <span class="absolute icon-feather-edit mr-4 text-xl uk-position-center-right cursor-pointer"></span>
                    </div>
                    <div class="messages-inbox-inner" data-simplebar>
                        <ul>
                            
                            {% for m in groupchat_list %}
                                <li>
                                    <a href="{% url 'core:group_inbox_detail' m.slug %}">
                                        <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{m.images.url}}" alt=""></div>

                                        <div class="message-by">
                                            <div class="message-by-headline">
                                                <h5>{{m.name}}</h5>
                                            </div>
                                            <p>{{m.last_message.message|truncatechars:40}}</p>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>


                <div class="message-content">

                    <div class="messages-headline">
                        <div class="flex">
                            <img class="mr-1" src="{{ groupchat.images.url }}" style="width: 40px; height: 40px; object-fit: cover; border-radius: 50%;" alt="">
                            <div>
                                <h4 class="ml-1"> {{ groupchat.name }} </h4>
                                <p style="font-size: 13px; margin-top: -12px;">{{groupchat.members.all.count}} Members</p>
                            </div>
                        </div>
                        <a href="{% url 'core:leave_group_chat' groupchat.slug  %}" class="message-action text-red-500"><i class="fas fa-sign-out-alt"></i> <span class="md:inline hidden">Leave Group</span> </a>
                    </div>

                    <div class="message-content-scrolbar" data-simplebar>

                        <!-- Message Content Inner -->
                        <div class="message-content-inner chat_container" style="overflow-y: scroll; max-height: 550px; height: auto; ">

                            <!-- Time Sign -->
                            <div class="message-time-sign">
                                <span>Created on {{groupchat.date|date:"d M, Y"}}</span>
                            </div>

                            
                            {% comment %} {% for m in group_messages %}
                            
                                {% if m.sender == request.user %}
                                    <div class="message-bubble me">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ m.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <p>{{m.message}}</p>
                                                <p style="color: rgba(255, 255, 255, 0.479);"><small>{{ m.date|timesince }} ago - {{ m.sender.profile.full_name }}</small></p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% else %}
                                    <div class="message-bubble">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ m.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <p>{{m.message}}</p>
                                                <p style="color: gray"><small>{{ m.date|timesince }} ago - {{ m.sender.profile.full_name }}</small></p>

                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% endif %}
                            {% endfor %} {% endcomment %}
                            {% for m in group_messages %}
                                {% if m.sender == request.user %}
                                    <div class="message-bubble me">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ m.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <div class="message-metadata">
                                                    <strong>{{ m.sender.profile.full_name }}</strong> <time class="activity"><small>{{ m.date|timesince }} ago</small></time>
                                                </div>
                                                <p>{{m.message}}</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% else %}
                                    <div class="message-bubble">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ m.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <div class="message-metadata">
                                                    <strong>{{ m.sender.profile.full_name }}</strong> <time class="activity"><small>{{ m.date|timesince }} ago</small></time>
                                                </div>
                                                <p>{{m.message}}</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <div id="chat-messages"></div>

                        </div>

                        <!-- Reply Area -->
                        <div class="message-reply">
                            <textarea id="chat-input" cols="1" rows="1" placeholder="Write Message"></textarea>
                            <button id="send-btn" class="button ripple-effect" >Send</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(function() {
            var group_name = "{{group_name}}";
            var groupchat_id = "{{groupchat.id}}";
            console.log(group_name);
            console.log(groupchat_id);
    
            var socket = new WebSocket('ws://' + window.location.host + '/ws/group-chat/' + group_name + '/');
    
            socket.onopen = function() {
                console.log('WebSocket connection established.');
            }
    
            socket.onmessage = function(event) {
                console.log(event);
                var data = JSON.parse(event.data);
                var message = data.message;
                var sender = data.sender;
                var profileImage = data.profile_image;
                var groupchat_id = data.groupchat_id;
                var full_name = data.full_name
                var date = data.date
                console.log(sender !== "{{request.user}}");
                if (sender === "{{request.user}}") {
                        var chatMessage = '<div class="message-bubble me">';
                        chatMessage += '<div class="message-bubble-inner">';
                        chatMessage += '<div class="message-avatar"><img src="' + profileImage + '" alt=""></div>';
                        chatMessage += '<div class="message-text">';
                        chatMessage += '<p>' + message + '</p>';
                        chatMessage += '<p style="color: rgba(255, 255, 255, 0.479);"><small>' + date + ' ago - ' + full_name + '</small></p>'

                        chatMessage += '</div>';
                        chatMessage += '</div>';
                        chatMessage += '<div class="clearfix"></div>';
                        chatMessage += '</div>';
                        // Append the chat message to the main div
                        $('#chat-messages').append(chatMessage);
                        // Get the chat container
                        var chatContainer = document.querySelector('.chat_container');
                        // Automatically scroll to the bottom of the message after sending.
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                } else {
                    var chatMessage = '<div class="message-bubble">';
                        chatMessage += '<div class="message-bubble-inner">';
                        chatMessage += '<div class="message-avatar"><img src="' + profileImage + '" alt=""></div>';
                        chatMessage += '<div class="message-text">';
                        chatMessage += '<p>' + message + '</p>';
                        chatMessage += '<p style="color: gray"><small>' + date + ' ago - ' + full_name + '</small></p>'
                        chatMessage += '</div>';
                        chatMessage += '</div>';
                        chatMessage += '<div class="clearfix"></div>';
                        chatMessage += '</div>';
                        $('#chat-messages').append(chatMessage);

                        var chatContainer = document.querySelector('.chat_container');
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                        console.log("No");
                }
            }
    
            socket.onclose = function() {
                console.log('WebSocket connection closed.');
            }
    
            $('#send-btn').on('click', function() {
                var input = $('#chat-input');
                var message = input.val();
                var sender = "{{request.user.username}}"; 
                var data = {
                    'message': message,
                    'sender': sender,
                    'groupchat_id': groupchat_id,
                };
                socket.send(JSON.stringify(data));
                input.val('');
                var sendButton = $('#send-btn');
                sendButton.prop('disabled', true);
                $(".chat_container").scrollTop(100000000000);
            });
    
        });


       


        $(document).ready(function() {
          $(".chat_container").scrollTop(100000000000);
        });

    </script>

    <script>
       $(document).ready(function() {
            var chatInputValue = $('#chat-input');
            var sendButton = $('#send-btn');

            // Disable the button initially
            sendButton.prop('disabled', true);

            // Check input field on keyup event
            chatInputValue.on('keyup', function() {
                var inputText = $(this).val();

                // Enable/disable button based on input field value
                if (inputText.trim() !== '') {
                    sendButton.prop('disabled', false);
                } else {
                    sendButton.prop('disabled', true);
                }
            });
        })
    </script>


    

    {% endblock content %}